### ISSUE TITLE
2-dimensional arrays in enum

### ISSUE THREAD

**Issue by justnonamenoname** [Southclaws/pawn#120]
as title says

я могу проспонсировать, вопрос цены?

**Comment by YashasSamaga** [comment]
Two dimensional arrays in enum is as good as 3-dimensional arrays.

```
enum E_ENUM
{
       Money, // value = 0
       Score,   // value = 1
       AdminLevel, //value = 2
       Name[24], //value = 3
       Wanted Level, //value = 27
       TwoDArray[5][5] // value = 28
}
new EnumArray[500][E_ENUM]; //E_ENUM is the total size

EnumArray[0][Score] = 0; //is as good as EnumArray[0][1]

EnumArray[0][TwoDArray][2][2] //I see the problem now
```

The problem is that PAWN does not store 2D arrays like 1D array (C/++ style arrays). It stores 2D arrays by storing the addresses of the sub arrays in an array (it is explained [here](http://forum.sa-mp.com/showthread.php?t=591705))

**Comment by CanerKaraca23** [comment]
@justnonamenoname hey, didn't find anywhere to contact you since you're not active on gtaforums anymore, i found this issue to write you. I hope you're well. Seems you're busy with your new lifetickle theory, very good work, good luck.

It seems samp addon is not getting updates anymore since you're busy with your theory. So, if you don't plan to update/maintain samp addon anymore, can you open source here to other users contribute it and may continue to maintain it? Thanks. I hope you're fine.
