### ISSUE TITLE
Compiling with multiple processors

### ISSUE THREAD

**Issue by mschnitzer** [Southclaws/pawn#82]
Hi,

is there a way to compile a script with multiple processors? If not, I'd like to suggest that :-)

**Comment by oscar-broman** [comment]
You're suggesting to refactor the entire codebase to try gaining what little is possible by using a multi-threaded design?

There's not much that can be done multi-threaded in a compiler like this, where everything is done in sequence.

**Comment by Y-Less** [comment]
It isn't easy, since pawn doesn't have multiple separate compilation units like, say, C.  Everything is essentially lumped together in one huge file then that is built, with ordering important fir sone things, notably tag returns and the pre-processor.  I.e. you can't compile some lower bits of the file as their meaning may change based on what is higher up but covered by a different core.

So pre-processing, tokenisation, and some dependency resolution is strictly sequential.  That just leaves bytecode generation.  This is slightly more amenable to parallelisation.  Once you have a list of parsed and independent functions, you could generate the code for each one in a separate core and collate the results.  The effects of this would improve the more optimisations were being done, which is currently very few indeed.  However, based on my experiences with some hugely complex scripts, the codegen phase is not the slowest part of the compiler.

So in short, what Slice said.

**Comment by Y-Less** [comment]
If it is speed that you are worried about, I'm sure there are many other improvements that could be made throughout the code to improve the sequential performance much more that multiple cores would.  Off the top of my head - a rope representation of source code for improved replacements speed, or hash based symbol lookup.  It might do both already, but there will be others.  Pawn wasn't designed for the huge scripts SA:MP throws at it, frankly the compiler actually does quite well despite it, but it wasn't engineered for extreme speed.

**Comment by mschnitzer** [comment]
```
You're suggesting to refactor the entire codebase to try gaining what little is possible by using a multi-threaded design?
```
That's just a suggestion. I don't know the details of the compiler. That's why I cannot say if it's possible or not.

```
If it is speed that you are worried about, I'm sure there are many other improvements that could be made throughout the code
```
Of course but I just thought this might be a nice idea.

**Comment by Y-Less** [comment]
The other thing is that using multiple cores doesn't always make things faster.  Splitting workloads up and syncing the results takes a lot of code, so much that often this overhead totally negates any possible improvements.

**Comment by mschnitzer** [comment]
> The other thing is that using multiple cores doesn't always make things faster.
I agree. Refactoring does the job in the most cases.

Yes, it was just a suggestion. When it's too much effort, I'm fine when this idea will be ignored. :smile:
